In [5]:
import torch 

In [6]:
min_range = 0 
max_range = 150e-6
number_of_configs = 10 # this will yield 11 config values, beacuse the intensity value 0 is an "extra" and it means don't stimulate

intensitiesArray = torch.linspace(min_range,max_range,number_of_configs+1)

print(intensitiesArray)

tensor([0.0000e+00, 1.5000e-05, 3.0000e-05, 4.5000e-05, 6.0000e-05, 7.5000e-05,
        9.0000e-05, 1.0500e-04, 1.2000e-04, 1.3500e-04, 1.5000e-04])


In [14]:
n_phos = 3

# predictions = np.linspace(0.,1.,n_phos)
# predictions = np.linspace(1.,0.,n_phos)
predictions = torch.rand(2,n_phos)
print(predictions)

tensor([[0.9923, 0.0821, 0.8359],
        [0.6791, 0.3584, 0.9790]])


In [21]:
# def pred_to_intensities(intensitiesArray, predictions):
#     activation_values = predictions * (intensitiesArray.max()-intensitiesArray.min())+intensitiesArray.min()
#     intensitiesArray = torch.tile(intensitiesArray,(len(predictions),1))
#     activation_values = intensitiesArray[torch.arange(len(intensitiesArray)),(torch.abs(intensitiesArray - activation_values.view(-1,1))).argmin(axis=1)]

#     return activation_values

def pred_to_intensities(intensitiesArray, predictions):
    activation_values = predictions * (intensitiesArray.max()-intensitiesArray.min())+intensitiesArray.min()
    intensitiesArray = torch.tile(intensitiesArray,(predictions.shape[1],1))
    activation_values = intensitiesArray[torch.arange(intensitiesArray.shape[0]),(torch.abs(intensitiesArray - activation_values.unsqueeze(2))).argmin(axis=2)]

    return activation_values

activation_values = pred_to_intensities(intensitiesArray,predictions)

print(activation_values)

torch.Size([3, 11])
tensor([[1.5000e-04, 1.5000e-05, 1.2000e-04],
        [1.0500e-04, 6.0000e-05, 1.5000e-04]])
